// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dioexngywmbwaouixflk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpb2V4bmd5d21id2FvdWl4ZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTM1MzAsImV4cCI6MjA3Mjk2OTUzMH0.vwlEH9Xl3ABlU8jjj441FVpa9paGBAJ-lTJlHa6WKa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});